/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddressInput = IDL.Record({
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const AddressId = IDL.Nat;
export const AppError = IDL.Variant({
  'rateLimitExceeded' : IDL.Null,
  'serverError' : IDL.Text,
  'validationError' : IDL.Text,
  'expired' : IDL.Null,
  'alreadyVoted' : IDL.Null,
  'alreadyExists' : IDL.Null,
  'invalidInput' : IDL.Text,
  'duplicateEntry' : IDL.Null,
  'minSpend' : IDL.Nat,
  'notFound' : IDL.Null,
  'limitExceeded' : IDL.Null,
  'unauthorized' : IDL.Null,
  'insufficientStock' : IDL.Null,
  'alreadyReviewed' : IDL.Null,
});
export const ProductId = IDL.Nat;
export const ReviewId = IDL.Nat;
export const QuestionId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const FlashSaleItem = IDL.Record({
  'discountedPriceInPaisa' : IDL.Nat,
  'discountPercent' : IDL.Nat,
  'productId' : ProductId,
  'quantityLimit' : IDL.Opt(IDL.Nat),
  'originalPriceInPaisa' : IDL.Nat,
  'soldCount' : IDL.Nat,
});
export const CreateFlashSaleInput = IDL.Record({
  'startTime' : Timestamp,
  'endTime' : Timestamp,
  'items' : IDL.Vec(FlashSaleItem),
  'titleBn' : IDL.Text,
  'titleEn' : IDL.Text,
});
export const FlashSaleId = IDL.Nat;
export const OrderItem = IDL.Record({
  'priceInPaisa' : IDL.Nat,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'titleEn' : IDL.Text,
});
export const CreateOrderInput = IDL.Record({
  'idempotencyKey' : IDL.Opt(IDL.Text),
  'shippingAddressId' : AddressId,
  'promoCode' : IDL.Opt(IDL.Text),
  'stripePaymentIntentId' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const OrderId = IDL.Nat;
export const ProductLabel = IDL.Record({
  'descriptionBn' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'authorBn' : IDL.Text,
  'authorEn' : IDL.Text,
  'titleBn' : IDL.Text,
  'titleEn' : IDL.Text,
});
export const Language = IDL.Variant({
  'bilingual' : IDL.Null,
  'bengali' : IDL.Null,
  'english' : IDL.Null,
});
export const Genre = IDL.Variant({
  'other' : IDL.Null,
  'biography' : IDL.Null,
  'nonFiction' : IDL.Null,
  'academic' : IDL.Null,
  'history' : IDL.Null,
  'bengaliClassics' : IDL.Null,
  'religion' : IDL.Null,
  'fiction' : IDL.Null,
  'childrens' : IDL.Null,
  'poetry' : IDL.Null,
  'science' : IDL.Null,
});
export const CreateProductInput = IDL.Record({
  'coverImageUrl' : IDL.Text,
  'info' : ProductLabel,
  'isbn' : IDL.Text,
  'publisher' : IDL.Text,
  'priceInPaisa' : IDL.Nat,
  'language' : Language,
  'stockCount' : IDL.Nat,
  'genre' : Genre,
  'publicationDate' : Timestamp,
});
export const PromoCodeId = IDL.Nat;
export const CreateReviewInput = IDL.Record({
  'bodyEn' : IDL.Text,
  'productId' : ProductId,
  'rating' : IDL.Nat,
  'titleEn' : IDL.Text,
});
export const AdminAnalytics = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'recentRevenueInPaisa' : IDL.Nat,
  'recentOrderCount' : IDL.Nat,
  'bestsellers' : IDL.Vec(IDL.Tuple(ProductId, IDL.Nat)),
  'totalUsers' : IDL.Nat,
  'totalRevenueInPaisa' : IDL.Nat,
});
export const AnalyticsEvent = IDL.Record({
  'userId' : IDL.Text,
  'productId' : IDL.Opt(ProductId),
  'orderId' : IDL.Opt(OrderId),
  'timestamp' : Timestamp,
  'amount' : IDL.Opt(IDL.Nat),
  'eventType' : IDL.Text,
});
export const CallerLoginStatus = IDL.Record({
  'lastLoginAt' : IDL.Opt(IDL.Int),
  'loginAttemptWindowSeconds' : IDL.Nat,
  'isLoggedIn' : IDL.Bool,
  'loginAttempts' : IDL.Nat,
  'rateLimitResetAt' : IDL.Opt(IDL.Int),
  'isRateLimited' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'preferredLanguage' : IDL.Variant({
    'bengali' : IDL.Null,
    'english' : IDL.Null,
  }),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'priceSnapshotInPaisa' : IDL.Nat,
  'addedAt' : Timestamp,
  'quantity' : IDL.Nat,
});
export const FlashSaleView = IDL.Record({
  'id' : FlashSaleId,
  'startTime' : Timestamp,
  'endTime' : Timestamp,
  'createdAt' : Timestamp,
  'isCurrentlyActive' : IDL.Bool,
  'items' : IDL.Vec(FlashSaleItem),
  'titleBn' : IDL.Text,
  'titleEn' : IDL.Text,
});
export const EnquiryStatus = IDL.Variant({
  'new' : IDL.Null,
  'replied' : IDL.Null,
  'viewed' : IDL.Null,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Text,
  'status' : EnquiryStatus,
  'aiReply' : IDL.Text,
  'enquiryType' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'refundRequested' : IDL.Null,
  'refunded' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const UserId = IDL.Principal;
export const StatusUpdate = IDL.Record({
  'status' : OrderStatus,
  'note' : IDL.Text,
  'updatedAt' : Timestamp,
});
export const Address = IDL.Record({
  'id' : AddressId,
  'city' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'fullName' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'isDefault' : IDL.Bool,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'totalInPaisa' : IDL.Nat,
  'status' : OrderStatus,
  'idempotencyKey' : IDL.Text,
  'userId' : UserId,
  'discountInPaisa' : IDL.Nat,
  'promoCodeApplied' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'estimatedDeliveryDate' : IDL.Opt(Timestamp),
  'courierNote' : IDL.Opt(IDL.Text),
  'statusHistory' : IDL.Vec(StatusUpdate),
  'updatedAt' : Timestamp,
  'shippingAddress' : Address,
  'stripePaymentIntentId' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const OrderedQuantityItem = IDL.Record({
  'totalOrdered' : IDL.Nat,
  'productTitle' : IDL.Text,
  'productId' : ProductId,
  'totalRevenue' : IDL.Nat,
});
export const ProductView = IDL.Record({
  'id' : ProductId,
  'coverImageUrl' : IDL.Text,
  'info' : ProductLabel,
  'isbn' : IDL.Text,
  'publisher' : IDL.Text,
  'createdAt' : Timestamp,
  'priceInPaisa' : IDL.Nat,
  'language' : Language,
  'averageRating' : IDL.Float64,
  'stockCount' : IDL.Nat,
  'genre' : Genre,
  'publicationDate' : Timestamp,
  'reviewCount' : IDL.Nat,
});
export const Review = IDL.Record({
  'id' : ReviewId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'bodyEn' : IDL.Text,
  'productId' : ProductId,
  'isVerifiedPurchase' : IDL.Bool,
  'rating' : IDL.Nat,
  'helpfulVotes' : IDL.Nat,
  'titleEn' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const PagedResult_1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'totalCount' : IDL.Nat,
  'items' : IDL.Vec(Enquiry),
});
export const AdminReviewView = IDL.Record({
  'id' : ReviewId,
  'isApproved' : IDL.Bool,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'bodyEn' : IDL.Text,
  'productId' : ProductId,
  'isVerifiedPurchase' : IDL.Bool,
  'rating' : IDL.Nat,
  'helpfulVotes' : IDL.Nat,
  'titleEn' : IDL.Text,
});
export const PagedResult = IDL.Record({
  'hasMore' : IDL.Bool,
  'totalCount' : IDL.Nat,
  'items' : IDL.Vec(AdminReviewView),
});
export const AnswerId = IDL.Nat;
export const Answer = IDL.Record({
  'id' : AnswerId,
  'createdAt' : Timestamp,
  'questionId' : QuestionId,
  'helpfulVotes' : IDL.Nat,
  'answerText' : IDL.Text,
  'answeredBy' : UserId,
});
export const ProductFilter = IDL.Record({
  'minRating' : IDL.Opt(IDL.Float64),
  'inStockOnly' : IDL.Bool,
  'minPriceInPaisa' : IDL.Opt(IDL.Nat),
  'language' : IDL.Opt(Language),
  'genre' : IDL.Opt(Genre),
  'searchQuery' : IDL.Opt(IDL.Text),
  'maxPriceInPaisa' : IDL.Opt(IDL.Nat),
});
export const SortField = IDL.Variant({
  'title' : IDL.Null,
  'publicationDate' : IDL.Null,
  'rating' : IDL.Null,
  'price' : IDL.Null,
});
export const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
export const ProductSort = IDL.Record({
  'field' : SortField,
  'order' : SortOrder,
});
export const PromoCode = IDL.Record({
  'id' : PromoCodeId,
  'validFrom' : Timestamp,
  'code' : IDL.Text,
  'maxUsageCount' : IDL.Opt(IDL.Nat),
  'createdAt' : Timestamp,
  'usageCount' : IDL.Nat,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
  'minSpendInPaisa' : IDL.Nat,
  'validUntil' : Timestamp,
});
export const Question = IDL.Record({
  'id' : QuestionId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'questionText' : IDL.Text,
  'askedBy' : UserId,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateProductInput = IDL.Record({
  'id' : ProductId,
  'coverImageUrl' : IDL.Opt(IDL.Text),
  'info' : IDL.Opt(ProductLabel),
  'isbn' : IDL.Opt(IDL.Text),
  'publisher' : IDL.Opt(IDL.Text),
  'priceInPaisa' : IDL.Opt(IDL.Nat),
  'language' : IDL.Opt(Language),
  'stockCount' : IDL.Opt(IDL.Nat),
  'genre' : IDL.Opt(Genre),
  'publicationDate' : IDL.Opt(Timestamp),
});
export const PromoCodeUpdateRequest = IDL.Record({
  'maxUsageCount' : IDL.Opt(IDL.Nat),
  'discountPercent' : IDL.Opt(IDL.Nat),
  'isActive' : IDL.Opt(IDL.Bool),
  'minSpendInPaisa' : IDL.Opt(IDL.Nat),
  'validUntil' : IDL.Opt(Timestamp),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAddress' : IDL.Func(
      [AddressInput],
      [IDL.Variant({ 'ok' : AddressId, 'err' : AppError })],
      [],
    ),
  'addToCart' : IDL.Func(
      [ProductId, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError })],
      [],
    ),
  'addToWishlist' : IDL.Func(
      [ProductId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError })],
      [],
    ),
  'adminApproveReview' : IDL.Func(
      [ReviewId, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
      [],
    ),
  'adminDeleteReview' : IDL.Func(
      [ReviewId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
      [],
    ),
  'askQuestion' : IDL.Func(
      [ProductId, IDL.Text],
      [IDL.Variant({ 'ok' : QuestionId, 'err' : AppError })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createFlashSale' : IDL.Func([CreateFlashSaleInput], [FlashSaleId], []),
  'createOrder' : IDL.Func(
      [CreateOrderInput],
      [IDL.Variant({ 'ok' : OrderId, 'err' : AppError })],
      [],
    ),
  'createProduct' : IDL.Func(
      [CreateProductInput],
      [IDL.Variant({ 'ok' : ProductId, 'err' : AppError })],
      [],
    ),
  'createPromoCode' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Nat, Timestamp, Timestamp],
      [IDL.Variant({ 'ok' : PromoCodeId, 'err' : AppError })],
      [],
    ),
  'createReview' : IDL.Func(
      [CreateReviewInput],
      [IDL.Variant({ 'ok' : ReviewId, 'err' : AppError })],
      [],
    ),
  'deactivateFlashSale' : IDL.Func([FlashSaleId], [IDL.Bool], []),
  'deactivatePromoCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteAddress' : IDL.Func([AddressId], [IDL.Bool], []),
  'deleteEnquiry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteMyReview' : IDL.Func(
      [ReviewId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
      [],
    ),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'downloadInvoice' : IDL.Func([OrderId], [IDL.Text], ['query']),
  'getAdminAnalytics' : IDL.Func([], [AdminAnalytics], []),
  'getAnalyticsEvents' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(AnalyticsEvent)],
      ['query'],
    ),
  'getCallerLoginStatus' : IDL.Func([], [CallerLoginStatus], ['query']),
  'getCallerPrincipal' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getDownloadStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getEnquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getFlashSale' : IDL.Func([FlashSaleId], [IDL.Opt(FlashSaleView)], ['query']),
  'getMyEnquiries' : IDL.Func([IDL.Text], [IDL.Vec(Enquiry)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrderedQuantityReport' : IDL.Func(
      [IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
      [IDL.Vec(OrderedQuantityItem)],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductView)], ['query']),
  'getRecentlyViewed' : IDL.Func([], [IDL.Vec(ProductView)], ['query']),
  'getReview' : IDL.Func([ReviewId], [IDL.Opt(Review)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTopProducts' : IDL.Func([IDL.Nat], [IDL.Vec(ProductView)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAddresses' : IDL.Func([], [IDL.Vec(Address)], ['query']),
  'listAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'listAllEnquiriesPaged' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PagedResult_1],
      ['query'],
    ),
  'listAllOrders' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Order)], ['query']),
  'listAllReturns' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listAllReviews' : IDL.Func([], [IDL.Vec(AdminReviewView)], ['query']),
  'listAllReviewsPaged' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PagedResult],
      ['query'],
    ),
  'listAnswers' : IDL.Func([QuestionId], [IDL.Vec(Answer)], ['query']),
  'listFlashSales' : IDL.Func([IDL.Bool], [IDL.Vec(FlashSaleView)], ['query']),
  'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listMyReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'listProducts' : IDL.Func(
      [IDL.Opt(ProductFilter), IDL.Opt(ProductSort), IDL.Nat, IDL.Nat],
      [IDL.Vec(ProductView)],
      ['query'],
    ),
  'listPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
  'listQuestions' : IDL.Func([ProductId], [IDL.Vec(Question)], ['query']),
  'listReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'listReviewsSorted' : IDL.Func(
      [
        ProductId,
        IDL.Variant({
          'helpfulness' : IDL.Null,
          'recency' : IDL.Null,
          'rating' : IDL.Null,
        }),
      ],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'ping' : IDL.Func([], [IDL.Bool], ['query']),
  'postAnswer' : IDL.Func(
      [QuestionId, IDL.Text],
      [IDL.Variant({ 'ok' : AnswerId, 'err' : AppError })],
      [],
    ),
  'pruneStaleRateLimits' : IDL.Func(
      [],
      [
        IDL.Record({
          'enquiryRateLimitsPruned' : IDL.Nat,
          'loginRateLimitsPruned' : IDL.Nat,
          'idempotencyKeysPruned' : IDL.Nat,
        }),
      ],
      [],
    ),
  'recordDownload' : IDL.Func([IDL.Text], [], []),
  'recordRecentlyViewed' : IDL.Func([ProductId], [], []),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'requestReturn' : IDL.Func(
      [OrderId, IDL.Text],
      [IDL.Variant({ 'ok' : OrderId, 'err' : AppError })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func(
      [UserProfile],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError })],
      [],
    ),
  'searchProducts' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(ProductView)],
      ['query'],
    ),
  'setDefaultAddress' : IDL.Func([AddressId], [IDL.Bool], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitChatEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'aiReply' : IDL.Text, 'enquiryId' : IDL.Text }),
          'err' : AppError,
        }),
      ],
      [],
    ),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : AppError })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAddress' : IDL.Func(
      [AddressId, AddressInput],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
      [],
    ),
  'updateCartQuantity' : IDL.Func(
      [ProductId, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError })],
      [],
    ),
  'updateEnquiryStatus' : IDL.Func([IDL.Text, EnquiryStatus], [IDL.Bool], []),
  'updateOrderStatus' : IDL.Func(
      [OrderId, OrderStatus, IDL.Text, IDL.Opt(IDL.Int), IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateProduct' : IDL.Func(
      [UpdateProductInput],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
      [],
    ),
  'updatePromoCode' : IDL.Func(
      [IDL.Text, PromoCodeUpdateRequest],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
      [],
    ),
  'updateStock' : IDL.Func([ProductId, IDL.Int], [IDL.Bool], []),
  'validatePromoCode' : IDL.Func([IDL.Text], [IDL.Opt(PromoCode)], ['query']),
  'voteAnswerHelpful' : IDL.Func(
      [AnswerId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
      [],
    ),
  'voteReviewHelpful' : IDL.Func(
      [ReviewId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddressInput = IDL.Record({
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const AddressId = IDL.Nat;
  const AppError = IDL.Variant({
    'rateLimitExceeded' : IDL.Null,
    'serverError' : IDL.Text,
    'validationError' : IDL.Text,
    'expired' : IDL.Null,
    'alreadyVoted' : IDL.Null,
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Text,
    'duplicateEntry' : IDL.Null,
    'minSpend' : IDL.Nat,
    'notFound' : IDL.Null,
    'limitExceeded' : IDL.Null,
    'unauthorized' : IDL.Null,
    'insufficientStock' : IDL.Null,
    'alreadyReviewed' : IDL.Null,
  });
  const ProductId = IDL.Nat;
  const ReviewId = IDL.Nat;
  const QuestionId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const FlashSaleItem = IDL.Record({
    'discountedPriceInPaisa' : IDL.Nat,
    'discountPercent' : IDL.Nat,
    'productId' : ProductId,
    'quantityLimit' : IDL.Opt(IDL.Nat),
    'originalPriceInPaisa' : IDL.Nat,
    'soldCount' : IDL.Nat,
  });
  const CreateFlashSaleInput = IDL.Record({
    'startTime' : Timestamp,
    'endTime' : Timestamp,
    'items' : IDL.Vec(FlashSaleItem),
    'titleBn' : IDL.Text,
    'titleEn' : IDL.Text,
  });
  const FlashSaleId = IDL.Nat;
  const OrderItem = IDL.Record({
    'priceInPaisa' : IDL.Nat,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'titleEn' : IDL.Text,
  });
  const CreateOrderInput = IDL.Record({
    'idempotencyKey' : IDL.Opt(IDL.Text),
    'shippingAddressId' : AddressId,
    'promoCode' : IDL.Opt(IDL.Text),
    'stripePaymentIntentId' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const OrderId = IDL.Nat;
  const ProductLabel = IDL.Record({
    'descriptionBn' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'authorBn' : IDL.Text,
    'authorEn' : IDL.Text,
    'titleBn' : IDL.Text,
    'titleEn' : IDL.Text,
  });
  const Language = IDL.Variant({
    'bilingual' : IDL.Null,
    'bengali' : IDL.Null,
    'english' : IDL.Null,
  });
  const Genre = IDL.Variant({
    'other' : IDL.Null,
    'biography' : IDL.Null,
    'nonFiction' : IDL.Null,
    'academic' : IDL.Null,
    'history' : IDL.Null,
    'bengaliClassics' : IDL.Null,
    'religion' : IDL.Null,
    'fiction' : IDL.Null,
    'childrens' : IDL.Null,
    'poetry' : IDL.Null,
    'science' : IDL.Null,
  });
  const CreateProductInput = IDL.Record({
    'coverImageUrl' : IDL.Text,
    'info' : ProductLabel,
    'isbn' : IDL.Text,
    'publisher' : IDL.Text,
    'priceInPaisa' : IDL.Nat,
    'language' : Language,
    'stockCount' : IDL.Nat,
    'genre' : Genre,
    'publicationDate' : Timestamp,
  });
  const PromoCodeId = IDL.Nat;
  const CreateReviewInput = IDL.Record({
    'bodyEn' : IDL.Text,
    'productId' : ProductId,
    'rating' : IDL.Nat,
    'titleEn' : IDL.Text,
  });
  const AdminAnalytics = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'recentRevenueInPaisa' : IDL.Nat,
    'recentOrderCount' : IDL.Nat,
    'bestsellers' : IDL.Vec(IDL.Tuple(ProductId, IDL.Nat)),
    'totalUsers' : IDL.Nat,
    'totalRevenueInPaisa' : IDL.Nat,
  });
  const AnalyticsEvent = IDL.Record({
    'userId' : IDL.Text,
    'productId' : IDL.Opt(ProductId),
    'orderId' : IDL.Opt(OrderId),
    'timestamp' : Timestamp,
    'amount' : IDL.Opt(IDL.Nat),
    'eventType' : IDL.Text,
  });
  const CallerLoginStatus = IDL.Record({
    'lastLoginAt' : IDL.Opt(IDL.Int),
    'loginAttemptWindowSeconds' : IDL.Nat,
    'isLoggedIn' : IDL.Bool,
    'loginAttempts' : IDL.Nat,
    'rateLimitResetAt' : IDL.Opt(IDL.Int),
    'isRateLimited' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'preferredLanguage' : IDL.Variant({
      'bengali' : IDL.Null,
      'english' : IDL.Null,
    }),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'priceSnapshotInPaisa' : IDL.Nat,
    'addedAt' : Timestamp,
    'quantity' : IDL.Nat,
  });
  const FlashSaleView = IDL.Record({
    'id' : FlashSaleId,
    'startTime' : Timestamp,
    'endTime' : Timestamp,
    'createdAt' : Timestamp,
    'isCurrentlyActive' : IDL.Bool,
    'items' : IDL.Vec(FlashSaleItem),
    'titleBn' : IDL.Text,
    'titleEn' : IDL.Text,
  });
  const EnquiryStatus = IDL.Variant({
    'new' : IDL.Null,
    'replied' : IDL.Null,
    'viewed' : IDL.Null,
  });
  const Enquiry = IDL.Record({
    'id' : IDL.Text,
    'status' : EnquiryStatus,
    'aiReply' : IDL.Text,
    'enquiryType' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'refundRequested' : IDL.Null,
    'refunded' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const StatusUpdate = IDL.Record({
    'status' : OrderStatus,
    'note' : IDL.Text,
    'updatedAt' : Timestamp,
  });
  const Address = IDL.Record({
    'id' : AddressId,
    'city' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'fullName' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'isDefault' : IDL.Bool,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'totalInPaisa' : IDL.Nat,
    'status' : OrderStatus,
    'idempotencyKey' : IDL.Text,
    'userId' : UserId,
    'discountInPaisa' : IDL.Nat,
    'promoCodeApplied' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'estimatedDeliveryDate' : IDL.Opt(Timestamp),
    'courierNote' : IDL.Opt(IDL.Text),
    'statusHistory' : IDL.Vec(StatusUpdate),
    'updatedAt' : Timestamp,
    'shippingAddress' : Address,
    'stripePaymentIntentId' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const OrderedQuantityItem = IDL.Record({
    'totalOrdered' : IDL.Nat,
    'productTitle' : IDL.Text,
    'productId' : ProductId,
    'totalRevenue' : IDL.Nat,
  });
  const ProductView = IDL.Record({
    'id' : ProductId,
    'coverImageUrl' : IDL.Text,
    'info' : ProductLabel,
    'isbn' : IDL.Text,
    'publisher' : IDL.Text,
    'createdAt' : Timestamp,
    'priceInPaisa' : IDL.Nat,
    'language' : Language,
    'averageRating' : IDL.Float64,
    'stockCount' : IDL.Nat,
    'genre' : Genre,
    'publicationDate' : Timestamp,
    'reviewCount' : IDL.Nat,
  });
  const Review = IDL.Record({
    'id' : ReviewId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'bodyEn' : IDL.Text,
    'productId' : ProductId,
    'isVerifiedPurchase' : IDL.Bool,
    'rating' : IDL.Nat,
    'helpfulVotes' : IDL.Nat,
    'titleEn' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const PagedResult_1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'totalCount' : IDL.Nat,
    'items' : IDL.Vec(Enquiry),
  });
  const AdminReviewView = IDL.Record({
    'id' : ReviewId,
    'isApproved' : IDL.Bool,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'bodyEn' : IDL.Text,
    'productId' : ProductId,
    'isVerifiedPurchase' : IDL.Bool,
    'rating' : IDL.Nat,
    'helpfulVotes' : IDL.Nat,
    'titleEn' : IDL.Text,
  });
  const PagedResult = IDL.Record({
    'hasMore' : IDL.Bool,
    'totalCount' : IDL.Nat,
    'items' : IDL.Vec(AdminReviewView),
  });
  const AnswerId = IDL.Nat;
  const Answer = IDL.Record({
    'id' : AnswerId,
    'createdAt' : Timestamp,
    'questionId' : QuestionId,
    'helpfulVotes' : IDL.Nat,
    'answerText' : IDL.Text,
    'answeredBy' : UserId,
  });
  const ProductFilter = IDL.Record({
    'minRating' : IDL.Opt(IDL.Float64),
    'inStockOnly' : IDL.Bool,
    'minPriceInPaisa' : IDL.Opt(IDL.Nat),
    'language' : IDL.Opt(Language),
    'genre' : IDL.Opt(Genre),
    'searchQuery' : IDL.Opt(IDL.Text),
    'maxPriceInPaisa' : IDL.Opt(IDL.Nat),
  });
  const SortField = IDL.Variant({
    'title' : IDL.Null,
    'publicationDate' : IDL.Null,
    'rating' : IDL.Null,
    'price' : IDL.Null,
  });
  const SortOrder = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
  const ProductSort = IDL.Record({ 'field' : SortField, 'order' : SortOrder });
  const PromoCode = IDL.Record({
    'id' : PromoCodeId,
    'validFrom' : Timestamp,
    'code' : IDL.Text,
    'maxUsageCount' : IDL.Opt(IDL.Nat),
    'createdAt' : Timestamp,
    'usageCount' : IDL.Nat,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
    'minSpendInPaisa' : IDL.Nat,
    'validUntil' : Timestamp,
  });
  const Question = IDL.Record({
    'id' : QuestionId,
    'createdAt' : Timestamp,
    'productId' : ProductId,
    'questionText' : IDL.Text,
    'askedBy' : UserId,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateProductInput = IDL.Record({
    'id' : ProductId,
    'coverImageUrl' : IDL.Opt(IDL.Text),
    'info' : IDL.Opt(ProductLabel),
    'isbn' : IDL.Opt(IDL.Text),
    'publisher' : IDL.Opt(IDL.Text),
    'priceInPaisa' : IDL.Opt(IDL.Nat),
    'language' : IDL.Opt(Language),
    'stockCount' : IDL.Opt(IDL.Nat),
    'genre' : IDL.Opt(Genre),
    'publicationDate' : IDL.Opt(Timestamp),
  });
  const PromoCodeUpdateRequest = IDL.Record({
    'maxUsageCount' : IDL.Opt(IDL.Nat),
    'discountPercent' : IDL.Opt(IDL.Nat),
    'isActive' : IDL.Opt(IDL.Bool),
    'minSpendInPaisa' : IDL.Opt(IDL.Nat),
    'validUntil' : IDL.Opt(Timestamp),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAddress' : IDL.Func(
        [AddressInput],
        [IDL.Variant({ 'ok' : AddressId, 'err' : AppError })],
        [],
      ),
    'addToCart' : IDL.Func(
        [ProductId, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError })],
        [],
      ),
    'addToWishlist' : IDL.Func(
        [ProductId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError })],
        [],
      ),
    'adminApproveReview' : IDL.Func(
        [ReviewId, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
        [],
      ),
    'adminDeleteReview' : IDL.Func(
        [ReviewId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
        [],
      ),
    'askQuestion' : IDL.Func(
        [ProductId, IDL.Text],
        [IDL.Variant({ 'ok' : QuestionId, 'err' : AppError })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createFlashSale' : IDL.Func([CreateFlashSaleInput], [FlashSaleId], []),
    'createOrder' : IDL.Func(
        [CreateOrderInput],
        [IDL.Variant({ 'ok' : OrderId, 'err' : AppError })],
        [],
      ),
    'createProduct' : IDL.Func(
        [CreateProductInput],
        [IDL.Variant({ 'ok' : ProductId, 'err' : AppError })],
        [],
      ),
    'createPromoCode' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Nat, Timestamp, Timestamp],
        [IDL.Variant({ 'ok' : PromoCodeId, 'err' : AppError })],
        [],
      ),
    'createReview' : IDL.Func(
        [CreateReviewInput],
        [IDL.Variant({ 'ok' : ReviewId, 'err' : AppError })],
        [],
      ),
    'deactivateFlashSale' : IDL.Func([FlashSaleId], [IDL.Bool], []),
    'deactivatePromoCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteAddress' : IDL.Func([AddressId], [IDL.Bool], []),
    'deleteEnquiry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteMyReview' : IDL.Func(
        [ReviewId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
        [],
      ),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'downloadInvoice' : IDL.Func([OrderId], [IDL.Text], ['query']),
    'getAdminAnalytics' : IDL.Func([], [AdminAnalytics], []),
    'getAnalyticsEvents' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(AnalyticsEvent)],
        ['query'],
      ),
    'getCallerLoginStatus' : IDL.Func([], [CallerLoginStatus], ['query']),
    'getCallerPrincipal' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getDownloadStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getEnquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getFlashSale' : IDL.Func(
        [FlashSaleId],
        [IDL.Opt(FlashSaleView)],
        ['query'],
      ),
    'getMyEnquiries' : IDL.Func([IDL.Text], [IDL.Vec(Enquiry)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrderedQuantityReport' : IDL.Func(
        [IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
        [IDL.Vec(OrderedQuantityItem)],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductView)], ['query']),
    'getRecentlyViewed' : IDL.Func([], [IDL.Vec(ProductView)], ['query']),
    'getReview' : IDL.Func([ReviewId], [IDL.Opt(Review)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTopProducts' : IDL.Func([IDL.Nat], [IDL.Vec(ProductView)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAddresses' : IDL.Func([], [IDL.Vec(Address)], ['query']),
    'listAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'listAllEnquiriesPaged' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PagedResult_1],
        ['query'],
      ),
    'listAllOrders' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Order)], ['query']),
    'listAllReturns' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listAllReviews' : IDL.Func([], [IDL.Vec(AdminReviewView)], ['query']),
    'listAllReviewsPaged' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PagedResult],
        ['query'],
      ),
    'listAnswers' : IDL.Func([QuestionId], [IDL.Vec(Answer)], ['query']),
    'listFlashSales' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(FlashSaleView)],
        ['query'],
      ),
    'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listMyReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'listProducts' : IDL.Func(
        [IDL.Opt(ProductFilter), IDL.Opt(ProductSort), IDL.Nat, IDL.Nat],
        [IDL.Vec(ProductView)],
        ['query'],
      ),
    'listPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
    'listQuestions' : IDL.Func([ProductId], [IDL.Vec(Question)], ['query']),
    'listReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
    'listReviewsSorted' : IDL.Func(
        [
          ProductId,
          IDL.Variant({
            'helpfulness' : IDL.Null,
            'recency' : IDL.Null,
            'rating' : IDL.Null,
          }),
        ],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'ping' : IDL.Func([], [IDL.Bool], ['query']),
    'postAnswer' : IDL.Func(
        [QuestionId, IDL.Text],
        [IDL.Variant({ 'ok' : AnswerId, 'err' : AppError })],
        [],
      ),
    'pruneStaleRateLimits' : IDL.Func(
        [],
        [
          IDL.Record({
            'enquiryRateLimitsPruned' : IDL.Nat,
            'loginRateLimitsPruned' : IDL.Nat,
            'idempotencyKeysPruned' : IDL.Nat,
          }),
        ],
        [],
      ),
    'recordDownload' : IDL.Func([IDL.Text], [], []),
    'recordRecentlyViewed' : IDL.Func([ProductId], [], []),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'requestReturn' : IDL.Func(
        [OrderId, IDL.Text],
        [IDL.Variant({ 'ok' : OrderId, 'err' : AppError })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func(
        [UserProfile],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError })],
        [],
      ),
    'searchProducts' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(ProductView)],
        ['query'],
      ),
    'setDefaultAddress' : IDL.Func([AddressId], [IDL.Bool], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitChatEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'aiReply' : IDL.Text, 'enquiryId' : IDL.Text }),
            'err' : AppError,
          }),
        ],
        [],
      ),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : AppError })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAddress' : IDL.Func(
        [AddressId, AddressInput],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
        [],
      ),
    'updateCartQuantity' : IDL.Func(
        [ProductId, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AppError })],
        [],
      ),
    'updateEnquiryStatus' : IDL.Func([IDL.Text, EnquiryStatus], [IDL.Bool], []),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus, IDL.Text, IDL.Opt(IDL.Int), IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateProduct' : IDL.Func(
        [UpdateProductInput],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
        [],
      ),
    'updatePromoCode' : IDL.Func(
        [IDL.Text, PromoCodeUpdateRequest],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
        [],
      ),
    'updateStock' : IDL.Func([ProductId, IDL.Int], [IDL.Bool], []),
    'validatePromoCode' : IDL.Func([IDL.Text], [IDL.Opt(PromoCode)], ['query']),
    'voteAnswerHelpful' : IDL.Func(
        [AnswerId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
        [],
      ),
    'voteReviewHelpful' : IDL.Func(
        [ReviewId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : AppError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };