/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'id' : AddressId,
  'city' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'fullName' : string,
  'line1' : string,
  'line2' : string,
  'district' : string,
  'state' : string,
  'isDefault' : boolean,
  'phone' : string,
  'pincode' : string,
}
export type AddressId = bigint;
export interface AddressInput {
  'city' : string,
  'fullName' : string,
  'line1' : string,
  'line2' : string,
  'district' : string,
  'state' : string,
  'phone' : string,
  'pincode' : string,
}
export interface AdminAnalytics {
  'totalProducts' : bigint,
  'totalOrders' : bigint,
  'recentRevenueInPaisa' : bigint,
  'recentOrderCount' : bigint,
  'bestsellers' : Array<[ProductId, bigint]>,
  'totalUsers' : bigint,
  'totalRevenueInPaisa' : bigint,
}
export interface AdminReviewView {
  'id' : ReviewId,
  'isApproved' : boolean,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'bodyEn' : string,
  'productId' : ProductId,
  'isVerifiedPurchase' : boolean,
  'rating' : bigint,
  'helpfulVotes' : bigint,
  'titleEn' : string,
}
export interface AnalyticsEvent {
  'userId' : string,
  'productId' : [] | [ProductId],
  'orderId' : [] | [OrderId],
  'timestamp' : Timestamp,
  'amount' : [] | [bigint],
  'eventType' : string,
}
export interface Answer {
  'id' : AnswerId,
  'createdAt' : Timestamp,
  'questionId' : QuestionId,
  'helpfulVotes' : bigint,
  'answerText' : string,
  'answeredBy' : UserId,
}
export type AnswerId = bigint;
export type AppError = { 'rateLimitExceeded' : null } |
  { 'serverError' : string } |
  { 'validationError' : string } |
  { 'expired' : null } |
  { 'alreadyVoted' : null } |
  { 'alreadyExists' : null } |
  { 'invalidInput' : string } |
  { 'duplicateEntry' : null } |
  { 'minSpend' : bigint } |
  { 'notFound' : null } |
  { 'limitExceeded' : null } |
  { 'unauthorized' : null } |
  { 'insufficientStock' : null } |
  { 'alreadyReviewed' : null };
export interface CartItem {
  'productId' : ProductId,
  'priceSnapshotInPaisa' : bigint,
  'addedAt' : Timestamp,
  'quantity' : bigint,
}
export interface CreateFlashSaleInput {
  'startTime' : Timestamp,
  'endTime' : Timestamp,
  'items' : Array<FlashSaleItem>,
  'titleBn' : string,
  'titleEn' : string,
}
export interface CreateOrderInput {
  'idempotencyKey' : [] | [string],
  'shippingAddressId' : AddressId,
  'promoCode' : [] | [string],
  'stripePaymentIntentId' : string,
  'items' : Array<OrderItem>,
}
export interface CreateProductInput {
  'coverImageUrl' : string,
  'info' : ProductLabel,
  'isbn' : string,
  'publisher' : string,
  'priceInPaisa' : bigint,
  'language' : Language,
  'stockCount' : bigint,
  'genre' : Genre,
  'publicationDate' : Timestamp,
}
export interface CreateReviewInput {
  'bodyEn' : string,
  'productId' : ProductId,
  'rating' : bigint,
  'titleEn' : string,
}
export interface Enquiry {
  'id' : string,
  'status' : EnquiryStatus,
  'aiReply' : string,
  'enquiryType' : string,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type EnquiryStatus = { 'new' : null } |
  { 'replied' : null } |
  { 'viewed' : null };
export type FlashSaleId = bigint;
export interface FlashSaleItem {
  'discountedPriceInPaisa' : bigint,
  'discountPercent' : bigint,
  'productId' : ProductId,
  'quantityLimit' : [] | [bigint],
  'originalPriceInPaisa' : bigint,
  'soldCount' : bigint,
}
export interface FlashSaleView {
  'id' : FlashSaleId,
  'startTime' : Timestamp,
  'endTime' : Timestamp,
  'createdAt' : Timestamp,
  'isCurrentlyActive' : boolean,
  'items' : Array<FlashSaleItem>,
  'titleBn' : string,
  'titleEn' : string,
}
export type Genre = { 'other' : null } |
  { 'biography' : null } |
  { 'nonFiction' : null } |
  { 'academic' : null } |
  { 'history' : null } |
  { 'bengaliClassics' : null } |
  { 'religion' : null } |
  { 'fiction' : null } |
  { 'childrens' : null } |
  { 'poetry' : null } |
  { 'science' : null };
export type Language = { 'bilingual' : null } |
  { 'bengali' : null } |
  { 'english' : null };
export interface Order {
  'id' : OrderId,
  'totalInPaisa' : bigint,
  'status' : OrderStatus,
  'idempotencyKey' : string,
  'userId' : UserId,
  'discountInPaisa' : bigint,
  'promoCodeApplied' : [] | [string],
  'createdAt' : Timestamp,
  'estimatedDeliveryDate' : [] | [Timestamp],
  'courierNote' : [] | [string],
  'statusHistory' : Array<StatusUpdate>,
  'updatedAt' : Timestamp,
  'shippingAddress' : Address,
  'stripePaymentIntentId' : string,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'priceInPaisa' : bigint,
  'productId' : ProductId,
  'quantity' : bigint,
  'titleEn' : string,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'refundRequested' : null } |
  { 'refunded' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface OrderedQuantityItem {
  'totalOrdered' : bigint,
  'productTitle' : string,
  'productId' : ProductId,
  'totalRevenue' : bigint,
}
export interface PagedResult {
  'hasMore' : boolean,
  'totalCount' : bigint,
  'items' : Array<AdminReviewView>,
}
export interface PagedResult_1 {
  'hasMore' : boolean,
  'totalCount' : bigint,
  'items' : Array<Enquiry>,
}
export interface ProductFilter {
  'minRating' : [] | [number],
  'inStockOnly' : boolean,
  'minPriceInPaisa' : [] | [bigint],
  'language' : [] | [Language],
  'genre' : [] | [Genre],
  'searchQuery' : [] | [string],
  'maxPriceInPaisa' : [] | [bigint],
}
export type ProductId = bigint;
export interface ProductLabel {
  'descriptionBn' : string,
  'descriptionEn' : string,
  'authorBn' : string,
  'authorEn' : string,
  'titleBn' : string,
  'titleEn' : string,
}
export interface ProductSort { 'field' : SortField, 'order' : SortOrder }
export interface ProductView {
  'id' : ProductId,
  'coverImageUrl' : string,
  'info' : ProductLabel,
  'isbn' : string,
  'publisher' : string,
  'createdAt' : Timestamp,
  'priceInPaisa' : bigint,
  'language' : Language,
  'averageRating' : number,
  'stockCount' : bigint,
  'genre' : Genre,
  'publicationDate' : Timestamp,
  'reviewCount' : bigint,
}
export interface PromoCode {
  'id' : PromoCodeId,
  'validFrom' : Timestamp,
  'code' : string,
  'maxUsageCount' : [] | [bigint],
  'createdAt' : Timestamp,
  'usageCount' : bigint,
  'discountPercent' : bigint,
  'isActive' : boolean,
  'minSpendInPaisa' : bigint,
  'validUntil' : Timestamp,
}
export type PromoCodeId = bigint;
export interface PromoCodeUpdateRequest {
  'maxUsageCount' : [] | [bigint],
  'discountPercent' : [] | [bigint],
  'isActive' : [] | [boolean],
  'minSpendInPaisa' : [] | [bigint],
  'validUntil' : [] | [Timestamp],
}
export interface Question {
  'id' : QuestionId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'questionText' : string,
  'askedBy' : UserId,
}
export type QuestionId = bigint;
export interface Review {
  'id' : ReviewId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'bodyEn' : string,
  'productId' : ProductId,
  'isVerifiedPurchase' : boolean,
  'rating' : bigint,
  'helpfulVotes' : bigint,
  'titleEn' : string,
}
export type ReviewId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type SortField = { 'title' : null } |
  { 'publicationDate' : null } |
  { 'rating' : null } |
  { 'price' : null };
export type SortOrder = { 'asc' : null } |
  { 'desc' : null };
export interface StatusUpdate {
  'status' : OrderStatus,
  'note' : string,
  'updatedAt' : Timestamp,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateProductInput {
  'id' : ProductId,
  'coverImageUrl' : [] | [string],
  'info' : [] | [ProductLabel],
  'isbn' : [] | [string],
  'publisher' : [] | [string],
  'priceInPaisa' : [] | [bigint],
  'language' : [] | [Language],
  'stockCount' : [] | [bigint],
  'genre' : [] | [Genre],
  'publicationDate' : [] | [Timestamp],
}
export type UserId = Principal;
export interface UserProfile {
  'preferredLanguage' : { 'bengali' : null } |
    { 'english' : null },
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAddress' : ActorMethod<
    [AddressInput],
    { 'ok' : AddressId } |
      { 'err' : AppError }
  >,
  'addToCart' : ActorMethod<
    [ProductId, bigint],
    { 'ok' : null } |
      { 'err' : AppError }
  >,
  'addToWishlist' : ActorMethod<
    [ProductId],
    { 'ok' : null } |
      { 'err' : AppError }
  >,
  'adminApproveReview' : ActorMethod<
    [ReviewId, boolean],
    { 'ok' : boolean } |
      { 'err' : AppError }
  >,
  'adminDeleteReview' : ActorMethod<
    [ReviewId],
    { 'ok' : boolean } |
      { 'err' : AppError }
  >,
  'askQuestion' : ActorMethod<
    [ProductId, string],
    { 'ok' : QuestionId } |
      { 'err' : AppError }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createFlashSale' : ActorMethod<[CreateFlashSaleInput], FlashSaleId>,
  'createOrder' : ActorMethod<
    [CreateOrderInput],
    { 'ok' : OrderId } |
      { 'err' : AppError }
  >,
  'createProduct' : ActorMethod<
    [CreateProductInput],
    { 'ok' : ProductId } |
      { 'err' : AppError }
  >,
  'createPromoCode' : ActorMethod<
    [string, bigint, [] | [bigint], bigint, Timestamp, Timestamp],
    { 'ok' : PromoCodeId } |
      { 'err' : AppError }
  >,
  'createReview' : ActorMethod<
    [CreateReviewInput],
    { 'ok' : ReviewId } |
      { 'err' : AppError }
  >,
  'deactivateFlashSale' : ActorMethod<[FlashSaleId], boolean>,
  'deactivatePromoCode' : ActorMethod<[string], boolean>,
  'deleteAddress' : ActorMethod<[AddressId], boolean>,
  'deleteEnquiry' : ActorMethod<[string], boolean>,
  'deleteMyReview' : ActorMethod<
    [ReviewId],
    { 'ok' : boolean } |
      { 'err' : AppError }
  >,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'downloadInvoice' : ActorMethod<[OrderId], string>,
  'getAdminAnalytics' : ActorMethod<[], AdminAnalytics>,
  'getAnalyticsEvents' : ActorMethod<[bigint, bigint], Array<AnalyticsEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getDownloadStats' : ActorMethod<[], Array<[string, bigint]>>,
  'getEnquiryCount' : ActorMethod<[], bigint>,
  'getFlashSale' : ActorMethod<[FlashSaleId], [] | [FlashSaleView]>,
  'getMyEnquiries' : ActorMethod<[string], Array<Enquiry>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrderedQuantityReport' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<OrderedQuantityItem>
  >,
  'getProduct' : ActorMethod<[ProductId], [] | [ProductView]>,
  'getRecentlyViewed' : ActorMethod<[], Array<ProductView>>,
  'getReview' : ActorMethod<[ReviewId], [] | [Review]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTopProducts' : ActorMethod<[bigint], Array<ProductView>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<ProductId>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAddresses' : ActorMethod<[], Array<Address>>,
  'listAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'listAllEnquiriesPaged' : ActorMethod<[bigint, bigint], PagedResult_1>,
  'listAllOrders' : ActorMethod<[bigint, bigint], Array<Order>>,
  'listAllReturns' : ActorMethod<[], Array<Order>>,
  'listAllReviews' : ActorMethod<[], Array<AdminReviewView>>,
  'listAllReviewsPaged' : ActorMethod<[bigint, bigint], PagedResult>,
  'listAnswers' : ActorMethod<[QuestionId], Array<Answer>>,
  'listFlashSales' : ActorMethod<[boolean], Array<FlashSaleView>>,
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  'listMyReviews' : ActorMethod<[], Array<Review>>,
  'listProducts' : ActorMethod<
    [[] | [ProductFilter], [] | [ProductSort], bigint, bigint],
    Array<ProductView>
  >,
  'listPromoCodes' : ActorMethod<[], Array<PromoCode>>,
  'listQuestions' : ActorMethod<[ProductId], Array<Question>>,
  'listReviews' : ActorMethod<[ProductId], Array<Review>>,
  'listReviewsSorted' : ActorMethod<
    [
      ProductId,
      { 'helpfulness' : null } |
        { 'recency' : null } |
        { 'rating' : null },
    ],
    Array<Review>
  >,
  'postAnswer' : ActorMethod<
    [QuestionId, string],
    { 'ok' : AnswerId } |
      { 'err' : AppError }
  >,
  'recordDownload' : ActorMethod<[string], undefined>,
  'recordRecentlyViewed' : ActorMethod<[ProductId], undefined>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'requestReturn' : ActorMethod<
    [OrderId, string],
    { 'ok' : OrderId } |
      { 'err' : AppError }
  >,
  'saveCallerUserProfile' : ActorMethod<
    [UserProfile],
    { 'ok' : null } |
      { 'err' : AppError }
  >,
  'searchProducts' : ActorMethod<[string, bigint], Array<ProductView>>,
  'setDefaultAddress' : ActorMethod<[AddressId], boolean>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitChatEnquiry' : ActorMethod<
    [string, string, string, string],
    { 'ok' : { 'aiReply' : string, 'enquiryId' : string } } |
      { 'err' : AppError }
  >,
  'submitEnquiry' : ActorMethod<
    [string, string, string, string],
    { 'ok' : string } |
      { 'err' : AppError }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAddress' : ActorMethod<
    [AddressId, AddressInput],
    { 'ok' : boolean } |
      { 'err' : AppError }
  >,
  'updateCartQuantity' : ActorMethod<
    [ProductId, bigint],
    { 'ok' : null } |
      { 'err' : AppError }
  >,
  'updateEnquiryStatus' : ActorMethod<[string, EnquiryStatus], boolean>,
  'updateOrderStatus' : ActorMethod<
    [OrderId, OrderStatus, string, [] | [bigint], [] | [string]],
    boolean
  >,
  'updateProduct' : ActorMethod<
    [UpdateProductInput],
    { 'ok' : boolean } |
      { 'err' : AppError }
  >,
  'updatePromoCode' : ActorMethod<
    [string, PromoCodeUpdateRequest],
    { 'ok' : boolean } |
      { 'err' : AppError }
  >,
  'updateStock' : ActorMethod<[ProductId, bigint], boolean>,
  'validatePromoCode' : ActorMethod<[string], [] | [PromoCode]>,
  'voteAnswerHelpful' : ActorMethod<
    [AnswerId],
    { 'ok' : boolean } |
      { 'err' : AppError }
  >,
  'voteReviewHelpful' : ActorMethod<
    [ReviewId],
    { 'ok' : boolean } |
      { 'err' : AppError }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];